CREATE TABLE TB_GROUP (
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(30) NOT NULL,
	UNIQUE UQ_TB_GROUP_1 (NAME),
	PRIMARY KEY(ID)
);

CREATE TABLE TB_CATEGORY (
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(30) NOT NULL,
	PID BIGINT UNSIGNED,
	CONSTRAINT FK_TB_CATEGORY_1 FOREIGN KEY (PID) REFERENCES TB_CATEGORY (ID) ON DELETE CASCADE,
	UNIQUE UQ_TB_CATEGORY_1 (NAME, PID),
	PRIMARY KEY(ID)
);

CREATE TABLE TB_USER (
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	UUID VARCHAR(30) NOT NULL,
	PASSWD VARCHAR(30) NOT NULL,
	FIRST_NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30) NOT NULL,
	DISPLAY_NAME VARCHAR(30) NOT NULL,
	MALE BIT(1) DEFAULT 1,
	BIRTHDAY DATE,
	ADDRESS VARCHAR(100),
	PHONE VARCHAR(50),
	MOBILE VARCHAR(50),
	SCORE INT UNSIGNED DEFAULT 0,
	UNIQUE UQ_TB_USER_1 (UUID),
	PRIMARY KEY(ID)
);

CREATE TABLE JN_USER_GROUP (
	USER_ID BIGINT UNSIGNED NOT NULL,
	GROUP_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT FK_JN_USER_GROUP_1 FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID) ON DELETE CASCADE,
	CONSTRAINT FK_JN_USER_GROUP_2 FOREIGN KEY (GROUP_ID) REFERENCES TB_GROUP (ID),
	PRIMARY KEY(USER_ID, GROUP_ID)
);

CREATE TABLE TB_ARTICLE (
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	SUBJECT VARCHAR(255) NOT NULL,
	CONTENT VARCHAR(255) NOT NULL,
	CREATED_TIME DATETIME NOT NULL,
	LAST_MODIFIED DATETIME NOT NULL,
	USER_ID BIGINT UNSIGNED NOT NULL,
	CATEGORY_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT FK_TB_ARTICLE_1 FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID) ON DELETE CASCADE,
	CONSTRAINT FK_TB_ARTICLE_2 FOREIGN KEY (CATEGORY_ID) REFERENCES TB_CATEGORY (ID),
	PRIMARY KEY(ID)
);

CREATE TABLE TB_REPLY (
	ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	CONTENT VARCHAR(255) NOT NULL,
	CREATED_TIME DATETIME NOT NULL,
	LAST_MODIFIED DATETIME NOT NULL,
	ARTICLE_ID BIGINT UNSIGNED NOT NULL,
	USER_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT FK_TB_REPLY_1 FOREIGN KEY (ARTICLE_ID) REFERENCES TB_ARTICLE (ID) ON DELETE CASCADE,
	CONSTRAINT FK_TB_REPLY_2 FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID) ON DELETE CASCADE,
	PRIMARY KEY(ID)
);